version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/go/src
    networks: 
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/go/src
    networks: 
      - app-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - app-network

  mysql:
    image: mysql:latest
    expose: 
      - 3306
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge